version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$ECR_REPO_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}    
  build:
    commands:
      - echo Build started on `date` v004
      - java -version
      - gradle assemble
      - docker build --build-arg  JAR_FILE=build/libs/ContactMe-1.jar   -t sel2in/contactmev002_$REPOSITORY_URI:latest .
      #- 637423423562.dkr.ecr.eu-north-1.amazonaws.com/jancfour1:latest
  post_build:
    commands:
      - echo Post build `date`
      - echo pushing $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - build/libs/ContactMe-1.jar
  discard-paths: yes
