version: 0.2

phases:
  pre_build:
    commands:
      - echo start pre `date`
      - REPOSITORY_URI=$ECR_REPO_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo commit hash $COMMIT_HASH.
      - echo img tag $IMAGE_TAG.
      - echo "sleep for 8 seconds"
      - sleep 8
      - echo "sleep for 4 seconds"
      - sleep 4
  build:
    commands:
      - echo Build started on `date` v004
      - java -version
      - echo $COMMIT_HASH>src/main/resources/tag
      - gradle assemble
      - docker build --build-arg  JAR_FILE=build/libs/ContactMe-1.jar   -t $REPOSITORY_URI:latest .
      #- 637423423562.dkr.ecr.eu-north-1.amazonaws.com/jancfour1:latest
  post_build:
    commands:
      - echo Post build `date`
      - echo COMMIT_HASH $COMMIT_HASH
      - echo pushing `$REPOSITORY_URI:latest`
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - build/libs/ContactMe-1.jar
  discard-paths: yes
